name: Publish preview update
on:
  push:
    branches: ['*']
jobs:
  publish_preview_update:
    name: Publish preview update
    if: ${{ contains(github.commit_message || '', '[ios]') }}
    type: update
    params:
      branch: ${{ github.ref_name || 'test' }}
